---
- name: Install gomon 
  # become: yes
  # become_method: sudo
  unarchive:
    src:  https://github.com/leominov/self-monitoring/releases/download/0.1.6/gomon-Linux-{{ arch }}.tar.gz
    dest: /tmp/
    remote_src: True