---
- name: Check if Gomon already downloaded
  stat:
    path: "{{ gomon_distrib_path }}"
  register: distrib

- include: configure.yaml
  become: yes

- include: install.yaml
  when: distrib.stat.exists == False
  become: yes
