---
- name: Create temp directory
  file:
    path: "/home/{{ ansible_ssh_user }}/tmp/"
    state: directory

- name: Install gomon 
  unarchive:
    src: "{{ gomon_download_url }}"
    dest: "/home/{{ ansible_ssh_user }}/tmp/"
    remote_src: True

- template:
    src: config.json.j2
    dest: "/home/{{ ansible_ssh_user }}/tmp/config.json"
